name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install kafka-python requests psycopg2-binary

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start Test Stack
        run: |
          docker-compose up -d
          sleep 90

      - name: Run Load Test
        run: |
          chmod +x tests/load_test.sh
          ./tests/load_test.sh

      - name: Validate Pipeline
        run: |
          python tests/validate_pipeline.py

      - name: Shutdown
        run: |
          docker-compose down